### ISSUE TITLE
501 Method PROPFIND is not defined in RFC 2068 and is not supported by the Servlet API

### ISSUE THREAD

**Issue by lulori** [cryptomator/cli#14]
trying to mount the webdav instance via davfs2 on raspberry pi/jessie is not working with the given error... using davfs2.

Maybe something with the webdav implementation has gone wrong.

**Comment by lulori** [comment]
trying to mount the webdav instance via davfs2 on raspberry pi/jessie is not working with the given error... using davfs2.

Maybe something with the webdav implementation has gone wrong.

**Comment by overheadhunter** [comment]
IMHO this is a misbehaviour of the WebDAV client software:
- `PROPFIND http://localhost/` <-- not supported
- `PROPFIND http://localhost/vaultPath/` <-- supported

There is actually no reason to PROPFIND the parent resource of a WebDAV resource.

But sometimes one needs to fix things, others did wrong (doing this for Windows all the time^^). So we recently [fixed this in the webdav library](https://github.com/cryptomator/webdav-nio-adapter/issues/11), which will affect the next CLI release.

**Comment by karl66** [comment]
I got the same error and I'm not sure what the vaultPath in http://localhost/vaultPath/ should be or where to find it. The Readme suggests its the Vault name but that doesn't work.

**Comment by shaiguitar** [comment]
Did a cli release get cut (0.3.1 or after) with the fix mentioned in last comment?

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
