### ISSUE TITLE
[MANUAL] How do I mount the Vault on *nix?

### ISSUE THREAD

**Issue by Dave3o3** [cryptomator/cli#17]
Maybe I'm just stupid or not experienced enough, but how do I mount the drive via http://localhost:8080/mysupervault3000?

**Comment by Dave3o3** [comment]
Well, I did it myself. So for anyone who's looking for a solution or entry point:

(On Debian) You need the davfs package installed and configured (in my case i only allowed the root user to mount those filesystems). Then you can
`sudo mount -t davfs http://localhost:8080/your/folder/ /media/your/mounted/folder`

**Comment by overheadhunter** [comment]
Thanks, I'll add this to the README.
