### ISSUE TITLE
Is there still any progress?

### ISSUE THREAD

**Issue by iamdeeff** [cryptomator/cli#22]
I really would like to have a stable cli release for my linux server. As of now I think Cryptomator is the best solution and the safest for cross-platform (linux, Mac & iOS in my case) data encryption. I would love to see this being developed to stable as it is now for desktops. Right now I am stil depending on Rclone which doesn't work on iOS and isn't as user friendly. So please help me 😄

**Comment by overheadhunter** [comment]
Project isn't dead, but focus of the core team is on Cryptomator 1.4.0 at the moment.

**Comment by shaiguitar** [comment]
@overheadhunter I'm happy to spend some spare time on the CLI also. I was hoping to get the WebDAV URL from command line context. It seems like the `Copy WebDAV URL` dropdown in Cryptomator GUI which produces things like `http://localhost:42427/t-gHEcGmS20t/NAME` is available, but not sure how to get this in the headless version. 

Initially figured https://github.com/cryptomator/cryptomator/blob/19cd0d70e75d6fbea4c08980e53c15be0e3e74d1/main/ui/src/main/java/org/cryptomator/ui/controllers/UnlockedController.java#L244-L250 might be the entrypoint for that, but seems to be heavily tied to UI elements and not sure how I would port that to the CLI version. 

Happy to help contribute. I managed to get Travis to build the fork of both Cryptomator and CLI, so I should be able to test with small diffs at the very least.

**Comment by alexanderadam** [comment]
@overheadhunter I don't need webdav support but I would love to have Cryptomator running without a GUI (because [42](https://github.com/cryptomator/cryptomator/issues/42) and [656](https://github.com/cryptomator/cryptomator/issues/656) it's unusable for be anyway at the moment). Is there a nogui option for Cryptomator to mount something or is there a nowebdav option for the CLI?

If not: can I open an issue somewhere for those?

**Comment by overheadhunter** [comment]
> Is there a nogui option for Cryptomator to mount something

Yes this is what this CLI repo is for.

> or is there a nowebdav option for the CLI?

WebDAV is used to mount drives. Without it, the application makes no sense. I don't know if this is what you want, but the only way to have a headless Cryptomator application running that is still able to mount the "cleartext" drives is by adding FUSE / Dokany support to CLI. For this you can of course add feature requests but I don't expect anyone to work on it in this repo with high priority.

**Comment by infeo** [comment]
We just released version [0.4.0](https://github.com/cryptomator/cli/releases/tag/0.4.0). So i would say there is progress^^
