### ISSUE TITLE
Invalid character/InvalidPassphraseException when using strong passwords on ARM

### ISSUE THREAD

**Issue by indiandragon** [cryptomator/cli#26]
In Raspberry Pi running Java 8 ARM,

When using strong passwords such as one containing strings such as '(' or ')', Cryptomator CLI command throws Invalid character & if the password is in the file it throws InvalidPassphraseException.

JCE unlimited strength policy files doesn't make any difference.

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
