### ISSUE TITLE
--passwordfile option to hide passwords

### ISSUE THREAD

**Issue by ejsmit** [cryptomator/cli#3]
To prevent passwords being visible in automation scripts I would like to be able to specify the name of a file containing the password instead of the actual password itself on the command line.  This means other people can look at the script itself and not see any passwords.   The script itself can even be publicly version controlled as long as the password file remains secure.

Many other tools allow this, with the password file typically placed in a chmod 700 folder (I currently use ~/.secure for other software tools) with chmod 600 permissions on the file itself (something for the docs maybe)

**Comment by eqyiel** [comment]
@ejsmit, do you know about command substitution?

For example, `echo $(head -n 1 ~/.secure/password-file)` - you can probably achieve what you want like this.

**Comment by overheadhunter** [comment]
We will implement this eventually. But as the workaround provided by @eqyiel works just fine, this isn't our highest priority right now.

**Comment by FZachlod** [comment]
@eqyiel @overheadhunter command line substitution is fine but the password will show up in the process list so any user that has access to the system can see the password of the currently open vaults. this is a major security breach.

**Comment by xelra** [comment]
@overheadhunter It won't just show up in the process list, it's also not possible (to my knowledge) to do this kind of command substituation on Windows.

It would be really great if the password file feature would be high priority. I cannot use the cli client at all before that.

**Comment by overheadhunter** [comment]
Fixed by PR #9.
