### ISSUE TITLE
Headless / CLI access to vaults

### ISSUE THREAD

**Issue by Zvezdin** [cryptomator/cli#30]
### Summary

There should be a way to access Cryptomator vaults without a UI interface. If I am SSH-ing into a target machine, I find no way to access a Cryptomator vault from there (and SSH x-forward is not an option since Cryptomator will stop after I disconnect over SSH). 

The Cryptomator CLI project seems like the perfect fit but it's been inactive for over 2 years already, and given that it uses cryptofs 1.4.0, I don't know if this is even compatible with recently created vaults. 

Cyberduck CLI does support Cryptomator vaults over the terminal but it seems only be for specific file transfers, not to mount a decrypted vault. 

I see no other viable alternatives and would like to ask how am I to approach this issue.

**Comment by overheadhunter** [comment]
> The Cryptomator CLI project seems like the perfect fit but it's been inactive for over 2 years already, and given that it uses cryptofs 1.4.0, I don't know if this is even compatible with recently created vaults.

We're currently working on Cryptomator 1.5.0, which will introduce a new vault format. This will require an update of this CLI project, as well.

**Comment by blockloop** [comment]
@overheadhunter now that 1.5 is released will the CLI be updated any time soon? I'd like to be able to run this on a headless server and do a restic backup nightly

**Comment by infeo** [comment]
Closed by 333c6ba8a91eea275d2f501e570e4d6678c81658
