### ISSUE TITLE
Feature request: allow WebDAV URL as back-end

### ISSUE THREAD

**Issue by fancsali** [cryptomator/cli#41]
For better inter-operability with tools like `rclone` it would be brilliant if alongside a directory as the vault path, one could specify a WebDAV url.

This would mean, one could use a combination of `rclone` and `cryptomator-cli` in limited environments, where a mount is not possible. (Perhaps foe permission reasons, or simply because of using something like [Termux](https://termux.com/))

**Comment by overheadhunter** [comment]
This can be achieved by combining [cloud-access-java](https://github.com/cryptomator/cloud-access-java) with [fuse-cloud-access-adapter](https://github.com/cryptomator/fuse-cloud-access-adapter) and a little bit of glue code.

This bypasses local fs (except for some caching) and reads and writes directly from/to the cloud.

If you want a ready-to-use solution, on Windows and Mac there is [Mountain Duck](https://mountainduck.io), but it is not CLI program.

**Comment by fancsali** [comment]
Well, the reason I was proposing this is to achive a fully CLI-based
solution for things like Linux servers...

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
