### ISSUE TITLE
Integrate into rclone

### ISSUE THREAD

**Issue by darkdragon-001** [cryptomator/cli#49]
Instead of writing the whole software from scratch, why not just writing a backend for the well-maintained [`rclone`](https://rclone.org/) tool? There is huge insterest (rclone/rclone#1647) in this feature.

**Comment by overheadhunter** [comment]
This would in fact be in our interest as well. I've added my 2 cents to the linked thread.

**Comment by kesenwang** [comment]
> This would in fact be in our interest as well. I've added my 2 cents to the linked thread.

I’m really hoping that this will materialize, put in my two cents ok rClone’s page but this would really make encrypting large amounts of existing data in the cloud much easier through rClones automations.

**Comment by infeo** [comment]
Since this is about rclone and not cryptomator-cli, I'closing the ticket.
