### ISSUE TITLE
Optionally protect WebDAV server with username/password

### ISSUE THREAD

**Issue by tobihagemann** [cryptomator/cli#5]

**Comment by markuskreusch** [comment]
Using username/password should also enforce usage of HTTPS to allow transfer of the data.

**Comment by overheadhunter** [comment]
Depends on [WebDAV NIO Adapter issue 5](/cryptomator/webdav-nio-adapter/issues/5).

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete. Additionally, this FR targets actually webdav nio adapter.
