### ISSUE TITLE
make a new release

### ISSUE THREAD

**Issue by revintec** [cryptomator/cli#53]
it has been almost a year since the last release -- 0.5.1 released Dec 22, 2021 -- latest as of writing
some dependent libraries receive bugfixes at the mean time(e.g. https://github.com/cryptomator/cryptofs/issues/141

is it possible to make a new release containing all latest fixes? thx

**Comment by wellloaded** [comment]
It is  such a shame this is not progressing. I also would like to point out that the java approach is not the best IMHO.

Any ways the lack of support for the cli prevents me from implementing cryptomator on my NASes.
This would be as simple as cryptomato-cli encrypts the files on my disk (local security) and the app use the unencrypted mounting point to operate beside this the cloud client would replicate such encrypted files to the cloud (no need to re-encrypt).
Simple, fast, efficient... and missing!

**Comment by greycubesgav** [comment]
I have created a new Pull Request here: https://github.com/cryptomator/cli/pull/56
This is a very quick hack to bump the underlaying versions of cryptofs (up to v2.6.5) and webdav-nio (up to v2.0.3).
It seems to work for me but I'm no Java guru so YMMV!

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
