### ISSUE TITLE
ERROR [CryptomatorCli:36] No vault specified.

### ISSUE THREAD

**Issue by beanstalkblue** [cryptomator/cli#6]
My masterkey.cryptomator file is located at `/home/me/vaults/cryptomator/masterkey.cryptomator`

I run the cli jar like so:

`java -jar cryptomator-cli-0.2.1.jar --bind 0.0.0.0 --port 8080 --vault cryptomator=/home/me/vaults/cryptomator/ --password=abc`

I copied the path and mountName from ~/.Cryptomator/settings.json

This produces the error:

> ERROR [CryptomatorCli:36] No vault specified.

Am I doing something wrong or is this a bug?

**Comment by markuskreusch** [comment]
The syntax for the password parameter is equal to the syntax for the vault. So:

´´´
java -jar cryptomator-cli-0.2.1.jar --bind 0.0.0.0 --port 8080 --vault cryptomator=/home/me/vaults/cryptomator/ --password cryptomator=abc
´´´

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
