### ISSUE TITLE
Cryptomator for a single file

### ISSUE THREAD

**Issue by nurmians** [cryptomator/cli#62]
I would be interested in using Cryptomator for encrypting/decrypting a single file with a password. Is this possible with a one-liner on the (linux) command line? If not, is there a tool you could recommend?

**Comment by overheadhunter** [comment]
Cryptomator isn't suited for this task (it will always produce more than just one file).

You can achieve this with tools like OpenSSL though: https://stackoverflow.com/a/16056298/4014509

**Comment by nurmians** [comment]
Thanks, I went with openSSL for my encryption needs.
