### ISSUE TITLE
symlink don't work with mount using davfs

### ISSUE THREAD

**Issue by Cletip** [cryptomator/cli#63]
Hello everyone,

As said in the title, and after having done 

`echo | sudo mount -t davfs -o username=,user,gid=1000,uid=1000 http://localhost:8080/demoVault/ /media/your/mounted/folder`

with the right option, my encrypted folder is mounted.

The problem: I have symlinks in this original folder, and when I mount it with cryptomator cli (not the original), well... there are no symlinks inside!

I've done some research, and I think davfs supports symlink (if I'm not mistaken), so it would come from cryptomator cli.

Thanks in advance for your reply.

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
