### ISSUE TITLE
How much closer is this to being “ready?”

### ISSUE THREAD

**Issue by muxketeer** [cryptomator/cli#66]
I know the front page says this is just in an experiment phase. But I’m wondering how close it is to ready? And how much risk am I taking, in my homelab, by using this to access my crytometer vaults?  Is this project aiming to be secure? Is it already secure? If no, how insecure is it?

**Comment by overheadhunter** [comment]
It is not "insecure" in regards to encryption, as it uses the same implementation as the GUI app.

The warning refers to the fact that this is scarcely maintained and we don't have the capabilities to react to issues in what people may deem an acceptable response time.

Also it lacks some features, e.g. the ability to migrate vaults to newer formats or the integrity checker, which makes it depend on the GUI app if you plan to use it for long-term data storage.

So in terms of data security, you don't need to worry about the confidentiality but rather about the availability.

**Comment by infeo** [comment]
We will rewrite the project in a different framework, throwing the old code away making this issue obsolete.
