### ISSUE TITLE
Vault Management Feature Request

### ISSUE THREAD

**Issue by slws** [cryptomator/cli#7]
CLI Functionality for:

Creation of new vaults, specifying location\name, & new password.
Removal of vaults from the GUI list, specifying location\name (& password?)

**Comment by markuskreusch** [comment]
The CLI version already allows to create new vaults. Only problem is you have to create an empty directory at the location of the vault first. Will fix that in the context of #8.

I think a feature influencing the GUI configuration will not make it into the CLI. The CLI has no connection/knowledge of GUI specifics and thats how we designed and want to keep it.
